import Head from "next/head";
import React from "react";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/image.js";
import { useState } from "react";
// import coel from "../static/coel.jpg";
// import design from "../public/design.png";
// import code from "../public/code.png";
// import collection from "../public/lego-collection.png";
// import forum from "../public/lego-forum.png";
// import marketplace from "../public/lego-marketplace.png";
// import fullMarket from "../public/lego-full-market.png";
// import notifications from "../public/lego-notifications.png";
// import event from "../public/Tower-event.png";
// import home from "../public/Tower-home.png";
// import tickets from "../public/Tower-tickets.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Coel Allen Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-10 md:px-20 bg-slate-800 lg:px-40 dark:bg-gray-800">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl">Made with Next.js</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className=" bg-gradient-to-br from-cyan-500 to-blue-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Coel Allen
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-gray-300">
              Full stack developer
            </h3>
            <div>
              <Image
                className="mx-auto rounded-full mt-10 md:h-96 md:w-192"
                src="/coel.jpg"
                alt="Stuff"
                width={200}
                height={100}
              />
            </div>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-200">
              {/* NOTE This is where my description/ intro tag goes */}
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillLinkedin />
            <AiFillGithub />
          </div>
        </section>
        {/* NOTE Second Page */}
        <section>
          <div>
            <h3 className="text-3xl py-1">Services I offer</h3>
            {/*NOTE This is more text to update.  The span is for anything I'd like to highlight such as links to projects or maybe codeworks */}
            <p className="text-md py-2 leading-8 text-gray-800">
              Lorem ipsum dolor sit amet consectetur, adipisicing elit.
              Assumenda voluptates consequatur quaerat
              <span className="text-teal-500">agencies</span> doloribus et
              corporis dolore, totam eius eaque magnam asperiores consequuntur
              modi voluptatum id exercitationem mollitia est! Alias, culpa.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800">
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Magni id
              architecto aliquid! Debitis nobis culpa totam consequatur,
              repellendus minima aliquam magni assumenda libero explicabo
              dolorem eos praesentium labore doloremque nulla!
            </p>
          </div>
          <div className="md:columns-2 lg:columns-2 my-10">
            <div className="text-center shadow-lg p-10 rounded-xl">
              <div className="flex justify-center">
                <Image
                  src="/design.png"
                  alt="design"
                  width={100}
                  height={100}
                />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              {/* NOTE more text describing design */}
              <p className="py-2">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum
                aperiam voluptate enim distinctio repellat voluptas modi
                reiciendis minima facilis natus aut, nulla, cumque expedita vel
                inventore voluptatem amet ipsa illo.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Lucid</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl">
              <div className="flex justify-center">
                <Image src="/code.png" alt="design" width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              {/* NOTE more text describing design */}
              <p className="py-2">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum
                aperiam voluptate enim distinctio repellat voluptas modi
                reiciendis minima facilis natus aut, nulla, cumque expedita vel
                inventore voluptatem amet ipsa illo.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Lucid</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Lorem ipsum dolor sit amet consectetur, adipisicing elit.
              Assumenda voluptates consequatur quaerat
              <span className="text-teal-500">agencies</span> doloribus et
              corporis dolore, totam eius eaque magnam asperiores consequuntur
              modi voluptatum id exercitationem mollitia est! Alias, culpa.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                src="/Tower-home.png"
                alt="Tower Home"
                height={1000}
                width={1000}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                src="/Tower-event.png"
                alt="Tower Event"
                height={1000}
                width={1000}
              />
            </div>
            {/* <div className="basis-1/4 flex-1">
              <Image
                className="rounded-lg object-cover"
                src="/Tower-tickets.png"
                alt="Tower Tickets"
                height={1000}
                width={1000}
              />
            </div> */}
          </div>
          <div>
            <p className="text-md py-2 leading-8 text-gray-800">
              Lorem ipsum dolor sit amet consectetur, adipisicing elit.
              Assumenda voluptates consequatur quaerat
              <span className="text-teal-500">agencies</span> doloribus et
              corporis dolore, totam eius eaque magnam asperiores consequuntur
              modi voluptatum id exercitationem mollitia est! Alias, culpa.
            </p>
            <div className="flex flex-col gap-10 lg:flex-row lg:flex-wrap">
              <div className="basis-1/3 flex-1">
                <Image
                  className="rounded-lg object-cover"
                  src="/lego-full-market.png"
                  alt="Marketplace Page"
                  height={1000}
                  width={1000}
                />
              </div>
              <div className="basis-1/3 flex-1">
                <Image
                  className="rounded-lg object-cover"
                  src="/lego-marketplace.png"
                  alt="Trade Modal"
                  height={1000}
                  width={1000}
                />
              </div>
              <div className="basis-1/3 flex-1">
                <Image
                  className="rounded-lg object-cover"
                  src="/lego-notifications.png"
                  alt="Notifications Example"
                  height={1000}
                  width={1000}
                />
              </div>
              <div className="basis-1/3 flex-1">
                <Image
                  className="rounded-lg object-cover"
                  src="/lego-forum2.png"
                  alt="Forum Page"
                  height={1000}
                  width={1000}
                />
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
